## Provision Spark ##

- name: Copy Jets3t properties file
  become: yes
  become_user: "{{ analytics_user }}"
  template: src=jets3t.j2 dest={{ analytics.home }}/spark-{{ spark_version }}-bin-hadoop2.7/conf/jets3t.properties mode=755 owner={{ analytics_user }} group={{ analytics_group }}


## Provision DS ##
- name: Install packages
  become: yes
  apt:
    name: "{{ item }}"
    state: installed
    update_cache: true
    cache_valid_time: 3600
  with_items:
    - gem
    - ruby
    - gnupg2

- name: Import rvm keys
  become: yes
  become_user: "{{ analytics_user }}"
  shell: command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import - && curl -sSL https://rvm.io/pkuczynski.asc | gpg2 --import -

- name: Install rvm
  become: yes
  become_user: "{{ analytics_user }}"
  shell: curl -sSL https://get.rvm.io | bash -s stable

- name: source ruby script
  become: yes
  become_user: "{{ analytics_user }}"
  shell: echo "source {{ analytics.base_path }}/.rvm/scripts/rvm" >> ~/.bashrc
  args:
    executable: /bin/bash

- name: Install latest ruby
  become: yes
  shell: "{{ analytics.base_path }}/.rvm/bin/rvm install ruby-2.6"

#- name: Set latest ruby as default
#  become: yes
#  become_user: "{{ analytics_user }}"
#  shell: "rvm --default use ruby-2.6"

#- name: Install latest ruby-dev
#  become: yes
#  apt:
#    name: "ruby2.6-dev"
#    state: installed
#    update_cache: true
#    cache_valid_time: 3600

- name: Install ruby-kafka
  gem:
     name: ruby-kafka
  become: yes
  become_user: "{{ analytics_user }}"

- name: Download Kafka-2.11
  become: yes
  become_user: "{{ analytics_user }}"
  get_url: url=http://downloads.mesosphere.com/kafka/assets/kafka_2.11-0.10.1.0.tgz dest={{ analytics.home }}/kafka_2.11-0.10.1.0.tgz force=no owner={{ analytics_user }} group={{ analytics_group }}
  tags:
    - kafka-provision

- name: Unarchive Kafka
  become: yes
  become_user: "{{ analytics_user }}"
  unarchive: src={{ analytics.soft_path }}/kafka_2.11-0.10.1.0.tgz dest={{ analytics.home }}/ copy=no owner={{ analytics_user }} group={{ analytics_group }} creates={{ analytics.home }}/kafka_2.11-0.10.1.0
  tags:
    - kafka-provision
