aroraas@3c22fb870dd9 sunbird % ssh -i "sunbird-lab.pem" ubuntu@52.66.87.122
Welcome to Ubuntu 16.04.7 LTS (GNU/Linux 4.4.0-1121-aws x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

12 packages can be updated.
0 updates are security updates.

New release '18.04.5 LTS' available.
Run 'do-release-upgrade' to upgrade to it.


*** System restart required ***
Last login: Thu Feb 25 00:47:44 2021 from 117.220.107.119
ubuntu@jenkins:~$ clear







ubuntu@jenkins:~$ sudo -i
sudo: unable to resolve host jenkins
root@jenkins:~# vi /var/lib/jenkins/workspace/Provision/dev/DataPipeline/AnalyticsSpark/ansible/roles/analytics-spark-provision/tasks/main.yml




















- name: source ruby script
  become: yes
  become_user: "{{ analytics_user }}"
  shell: echo "source {{ analytics.base_path }}/.rvm/scripts/rvm" >> ~/.bashrc
  args:
    executable: /bin/bash

- name: Install latest ruby
  become: yes
  shell: "{{ analytics.base_path }}/.rvm/bin/rvm install ruby-2.6"

#- name: Set latest ruby as default
#  become: yes
#  become_user: "{{ analytics_user }}"
#  shell: "rvm --default use ruby-2.6"

#- name: Install latest ruby-dev
#  become: yes
#  apt:
#    name: "ruby2.6-dev"
#    state: installed
#    update_cache: true
#    cache_valid_time: 3600

- name: Install ruby-kafka
  gem:
     name: ruby-kafka
  become: yes
  become_user: "{{ analytics_user }}"

- name: Download Kafka-2.11
  become: yes
  become_user: "{{ analytics_user }}"
  get_url: url=http://downloads.mesosphere.com/kafka/assets/kafka_2.11-0.10.1.0.tgz dest={{ analytics.home }}/kafka_2.11-0.10.1.0.tgz force=no owner={{ analytics_user }} group={{ analytics_group }}
  tags:
    - kafka-provision

- name: Unarchive Kafka
  become: yes
  become_user: "{{ analytics_user }}"
  unarchive: src={{ analytics.soft_path }}/kafka_2.11-0.10.1.0.tgz dest={{ analytics.home }}/ copy=no owner={{ analytics_user }} group={{ analytics_group }} creates={{ analytics.home }}/kafka_2.11-0.10.1.0
  tags:
    - kafka-provision
